In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
df= pd.read_excel("Iris.xlsx", index_col=None)
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
np.random.seed(1234)
x,y=df[df.columns[:-1]],df['class']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

# Arbol de decisiòn

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
arbol=DecisionTreeClassifier()

In [14]:
arbol.fit(xtrain,ytrain)
y_pred=arbol.predict(xtest)

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(ytest,y_pred)

0.9777777777777777

In [16]:
confusion_matrix(ytest,y_pred)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 12]], dtype=int64)

In [17]:
lista_clases=df['class'].unique()
lista_clases

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [19]:
# no dejo instalar graphviz en pc escuela, hacer en casa
import graphviz
from sklearn.tree import export_graphviz

ModuleNotFoundError: No module named 'graphviz'

# Bosque aleatorio

In [20]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier()
forest.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [21]:
ypred2=forest.predict(xtest)
accuracy_score(ytest,ypred2)

0.9555555555555556

In [22]:
confusion_matrix(ytest,ypred2)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  1, 11]], dtype=int64)

In [23]:
forest.score(xtrain,ytrain)

0.9904761904761905

# Bagging

In [25]:
from sklearn.ensemble import BaggingClassifier

In [26]:
bag =BaggingClassifier()
bag.fit(xtrain,ytrain)


BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [27]:
ypred3=bag.predict(xtest)
accuracy_score(ytest,ypred3)

0.9555555555555556

In [28]:
confusion_matrix(ytest,ypred3)

array([[16,  0,  0],
       [ 0, 16,  1],
       [ 0,  1, 11]], dtype=int64)

In [30]:
from sklearn.svm import SVC
df['class']=df['class'].astype('category')
df['class_code']=df['class'].cat.codes
df.head()

sepal_length  sepal_width  petal_length  petal_width        class  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

   class_code  
0           0  
1           0  
2           0  
3           0  
4           0

In [ ]:
y2=df['class_code']
xtrain,xtest,ytrain,ytest=train_test_split(x,y2,test_size=0.3)
bag2=BaggingClassifier(base_estimator=SVC())
bag2.fit(xtrain,ytrain)
