In [1]:
import pandas as pd
import numpy as np

In [2]:
# leer nombres col
df_nombres = pd.read_excel("col_names.xlsx", header= None)
df_nombres

0
0            Sample code number
1               Clump Thickness
2       Uniformity of Cell Size
3      Uniformity of Cell Shape
4             Marginal Adhesion
5   Single Epithelial Cell Size
6                   Bare Nuclei
7               Bland Chromatin
8               Normal Nucleoli
9                       Mitoses
10                        Class

In [4]:
nombres= df_nombres[0].tolist()
nombres

['Sample code number',
 'Clump Thickness',
 'Uniformity of Cell Size',
 'Uniformity of Cell Shape',
 'Marginal Adhesion',
 'Single Epithelial Cell Size',
 'Bare Nuclei',
 'Bland Chromatin',
 'Normal Nucleoli',
 'Mitoses',
 'Class']

In [6]:
df = pd.read_csv("breast-cancer-wisconsin.data",names=nombres)
df.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [8]:
df.columns=df.columns.str.replace(' ','_')
df.head()

Sample_code_number  Clump_Thickness  Uniformity_of_Cell_Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity_of_Cell_Shape  Marginal_Adhesion  Single_Epithelial_Cell_Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [9]:
df.set_index("Sample_code_number",inplace=True)

In [10]:
df.replace("?",np.NaN,inplace=True)
df.isnull().sum()

Clump_Thickness                 0
Uniformity_of_Cell_Size         0
Uniformity_of_Cell_Shape        0
Marginal_Adhesion               0
Single_Epithelial_Cell_Size     0
Bare_Nuclei                    16
Bland_Chromatin                 0
Normal_Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
df.isnull().sum()

Clump_Thickness                0
Uniformity_of_Cell_Size        0
Uniformity_of_Cell_Shape       0
Marginal_Adhesion              0
Single_Epithelial_Cell_Size    0
Bare_Nuclei                    0
Bland_Chromatin                0
Normal_Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [13]:
df.dtypes

Clump_Thickness                 int64
Uniformity_of_Cell_Size         int64
Uniformity_of_Cell_Shape        int64
Marginal_Adhesion               int64
Single_Epithelial_Cell_Size     int64
Bare_Nuclei                    object
Bland_Chromatin                 int64
Normal_Nucleoli                 int64
Mitoses                         int64
Class                           int64
dtype: object

In [14]:
df['Bare_Nuclei']=pd.to_numeric(df['Bare_Nuclei'])

In [16]:
# x es todo excepto ultima, y ultima
x=df[df.columns[0:-1]]
y=df[df.columns[-1]] #Class

In [30]:
from sklearn.model_selection import train_test_split
np.random.seed(1234)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y)

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score
lr=LogisticRegression()

In [32]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
y_pred=lr.predict(x_test)
accuracy_score(y_test,y_pred)

0.9463414634146341

In [34]:
confusion_matrix(y_test,y_pred)

array([[128,   5],
       [  6,  66]], dtype=int64)

In [35]:
cm=confusion_matrix(y_test,y_pred)
tn=cm[0][0]
fp=cm[0][1]
fn=cm[1][0]
tp=cm[1][1]
vpr=tp/(tp+fn)
vpr

0.9166666666666666

In [36]:
spc=tn/(tn+fp)
spc

0.9624060150375939

In [37]:
df['Class'].value_counts()

2    444
4    239
Name: Class, dtype: int64

In [39]:
from sklearn.preprocessing import StandardScaler
escalar=StandardScaler()
x2=escalar.fit_transform(x)

In [40]:
np.random.seed(1234)
x2_train,x2_test,y2_train,y2_test=train_test_split(x2,y,test_size=0.3,stratify=y)


In [41]:
lr2=LogisticRegression()
lr2.fit(x2_train,y2_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [42]:
y2_pred=lr2.predict(x2_test)
accuracy_score(y2_test,y2_pred)

0.9512195121951219

In [44]:
#maquina soporte vectorial
from sklearn.svm import LinearSVC,SVC
lsvm=LinearSVC(max_iter=10000)
lsvm.fit(x_train,y_train)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=10000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [46]:
y3_pred=lsvm.predict(x_test)
accuracy_score(y_test,y3_pred)

0.9512195121951219

In [47]:
confusion_matrix(y_test,y3_pred)

array([[127,   6],
       [  4,  68]], dtype=int64)

In [49]:
svm=SVC()
svm.fit(x_train,y_train)
y4_pred=svm.predict(x_test)
accuracy_score(y_test,y4_pred)

0.9365853658536586

In [50]:
confusion_matrix(y_test,y4_pred)

array([[120,  13],
       [  0,  72]], dtype=int64)